#!/bin/bash
#PBS -N train-polyp-bmamba
#PBS -q gpu
#PBS -l select=1:ncpus=8:ngpus=1:mem=64g
#PBS -l walltime=72:00:00
#PBS -j oe

# Change to the directory where the job was submitted
cd $PBS_O_WORKDIR

# Activate environment
source /home/soft/anaconda3/etc/profile.d/conda.sh
conda activate cod10
module load cuda

# Run the training script for Boundary-Aware Mamba on Polyp Segmentation
python train_polyp.py
